### ISSUE TITLE
Spanish misstranslation

### ISSUE THREAD

**Issue by hgdiaz** [syncfusion/blazor-locale#11]
Hi,

There's a misstranslation in the spanish resource file.
The translation for the word "clrear" is not "claro", in this context is "limpiar"
I've made a pull request. Please check if it's OK.

**Comment by jesusarockias** [comment]
@hgdiaz - We have merged your changes.

**Comment by hgdiaz** [comment]
Great! Thanks!

**Comment by rajendranr-5483** [comment]
Thanks @hgdiaz .
