### ISSUE TITLE
Spanish resource

### ISSUE THREAD

**Issue by BogdanJak** [syncfusion/blazor-locale#111]
Hi

The spanish file seems to be corrupted. I can't open it.

Regards 
Bogdan

**Comment by merinofg** [comment]
Spanish file has a bug on [line 2052](https://github.com/syncfusion/blazor-locale/blame/3eae8eef2314cbe77a07cd8f748eed1f4c5d0cd4/src/SfResources.es.resx#L2052C1-L2052C10). Removing the extra ```</data>``` will fix it.

**Comment by gsumankumar** [comment]
Resolved the reported issue in this https://github.com/syncfusion/blazor-locale/pull/119/commits/02fcb0b9531763ccd40cc1495d0a63e62a3bd0c2 commit.
