### ISSUE TITLE
FR - replace 'pâte' by 'coller'

### ISSUE THREAD

**Issue by DjeeBay** [syncfusion/blazor-locale#128]
Pâte means pasta.
It's needed to replace 'pâte' by 'coller'

(EN) to paste = (FR) coller

**Comment by kmuthukumarmkm** [comment]
Hi @DjeeBay 


We are using google translator as standard and checked with that for ‘pâte’ and the definition is 'paste.' Please refer to the Google Translator screenshot for your reference.

![image](https://github.com/syncfusion/blazor-locale/assets/33709971/edd0a971-3dca-447c-8866-9697d773cd02)

Please reach out if you have any questions or concerns regarding this.

Regards,
Muthukumar K

**Comment by DjeeBay** [comment]
Hi,

I think you didn't read me well.
"Pâte" in french means Pasta in english.

Google Translator doesn't have the context here so "paste" alone can mean multiple things.
Here you don't want to talk about food, you want to translate "TO PASTE", then you'll have "Coller" in french.

So try to translate "to paste", the verb on Google Translator and you'll see.
If it's still not enough maybe this screenshot from Google Chrome will help you :

![Capture d'écran 2023-10-18 202355](https://github.com/syncfusion/blazor-locale/assets/22008152/22cb4a04-f75f-48d2-b597-6633cc3b585a)

**Comment by BharatRamsf3693** [comment]
Hi @DjeeBay,

Thank you for your valuable information. The following PR has been merged to resolve this issue: [129](https://github.com/syncfusion/blazor-locale/pull/129).

Regards,
Bharat Ram H
