### ISSUE TITLE
Dutch translation mistake

### ISSUE THREAD

**Issue by rednaxLamington** [syncfusion/blazor-locale#13]
The Close button in a Dialog (Top Right). When you hover over it, it is translated as "Dichtbij" While this means "Nearby". The correct translation should be "Sluiten"

**Comment by pandiyarajm** [comment]
Hi @rednaxLamington ,

We have corrected the **Dialog - Close** locale constant as "Sluiten" and committed.

Regards,
Pandiyaraj

**Comment by rajendranr-5483** [comment]
@rednaxLamington ,

We close this thread now. You can raise pull request if any other correction in locale.
