### ISSUE TITLE
Missing > in file SfResources.he.resx

### ISSUE THREAD

**Issue by ferminolr** [syncfusion/blazor-locale#139]
In the file [SfResources.he.resx](https://github.com/syncfusion/blazor-locale/blob/master/src/SfResources.he.resx)
Is missing a > in the line 2644
https://github.com/search?q=repo%3Asyncfusion%2Fblazor-locale%20%D7%A9%D7%81%D7%95%D6%BC%D7%A8%D6%B8%D7%94&type=code
Fail to compile is not add the missing char.

**Comment by kmuthukumarmkm** [comment]
Hi @ferminolr 

Thanks for Notifying us.

We have resolved it from this https://github.com/syncfusion/blazor-locale/pull/144.

Regards,
Muthukumar K
