### ISSUE TITLE
SfResources.pt-BR.resx - Error in translating 'clear' into Portuguese

### ISSUE THREAD

**Issue by rogmauri** [syncfusion/blazor-locale#140]
The translations found in the file for 'clear' are as 'Claro'. The correct option, for the context of the action, would be 'Limpar'.

Found in the resource file:
Grid_ClearButton ->         Claro
PdfViewer_Clear ->	         Claro
PivotView_Clear ->	         Claro
PivotView_ClearFilter ->	 Claro
Uploader_Clear ->	         Claro

Below is the correct translation:
Grid_ClearButton ->	 Limpar
PdfViewer_Clear ->	         Limpar
PivotView_Clear ->	         Limpar
PivotView_ClearFilter ->	 Limpar
Uploader_Clear ->	         Limpar

**Comment by SasthaPrathap** [comment]
We corrected the reported incorrect translation of the Pivot Tabe component and published it in the master branch. Please refer to the GitHub link below.

pt-BR: [blazor-locale/src/SfResources.pt-BR.resx at master · syncfusion/blazor-locale (github.com)](https://github.com/syncfusion/blazor-locale/blob/master/src/SfResources.pt-BR.resx#L2574-L2579)
