### ISSUE TITLE
Change german localization "Säulen" -> Spalten

### ISSUE THREAD

**Issue by d-oit** [syncfusion/blazor-locale#17]
Use "Spalten" always instead of "Säulen" 
![image](https://user-images.githubusercontent.com/6849456/99403836-32d24a00-28eb-11eb-9333-570bb53c1b31.png)

**Comment by kmuthukumar23** [comment]
Hi @do-it-ger ,

Thanks for your information

We have updated and merged your reported changes in german culture. #19 

Also, you can contribute to this repository and request you to give a pull request for any changes. We will review and merge the changes in this repository.

Thanks,
Muthukumar K

**Comment by rajendranr-5483** [comment]
@d-oit ,

Thanks.

We are closing this thread now since there are no recent activities.
