### ISSUE TITLE
es of resource resx is full of errors

### ISSUE THREAD

**Issue by sa-riverar** [syncfusion/blazor-locale#70]
After correcting the error it throws a lot more errors
![Imagen1](https://user-images.githubusercontent.com/85707969/166850408-0cb5d86c-7f5f-4e34-9504-0308d6f47973.png)
.

**Comment by syncsiva** [comment]
@sa-riverar  We have checked `SfResources.es.resx` file and all other resx files and it's loading properly in editor as expected. Refer below image below,

![image](https://user-images.githubusercontent.com/18731572/166870520-98bb3077-a01d-4f72-9cf9-47e563015601.png)

Can you share the resx file you are using or else please use the latest resx files published in this repo.

**Comment by sa-riverar** [comment]
The file I just downloaded again from github is attached.
You can check line 15 in text editor is incorrect as in the screen I shared.
Please do download from github and try.

Thanks in advance.
Best regards,
Socrates A Rivera R
[SfResources.es.zip](https://github.com/syncfusion/blazor-locale/files/8636211/SfResources.es.zip)

**Comment by syncsiva** [comment]
Hi @sa-riverar 

We have checked the shared file, and it doesn't contain resource information. It's completely different from the file in this repo.
https://github.com/syncfusion/blazor-locale/blob/master/src/SfResources.es.resx

The shared file contains div elements and css styles instead of data and value like below,

```
  <data name="MultiSelect_UnSelectAllText" xml:space="preserve">
    <value>Deselecciona todo</value>
  </data>
```

Requesting to use the resx file in this repo and refer below documentation link for more details,
https://blazor.syncfusion.com/documentation/common/localization

**Comment by sa-riverar** [comment]
Hello @syncsiva 

The file shared was obtained from 
![image](https://user-images.githubusercontent.com/85707969/167221279-4172b041-efdd-41d9-9d33-e2f0ca694e55.png)

I can not download (I do not know how to) the file from the link you sent. If I try to navigate to the previous level it sends me to another route completely different.

Can you please share me the correct file (or say how to get it).

Thans in advance.
Best regards,
Socrates A Rivera R

**Comment by syncsiva** [comment]
Hi @sa-riverar,

You can download files via git checkout or just download the files directly as zip as follows,
![image](https://user-images.githubusercontent.com/18731572/167278118-d0d6530a-80b7-42d8-a24f-0112731a2224.png)

**Comment by sa-riverar** [comment]
Hello @syncsiva ,
Thank you very much for the tip to correctly download the file.
I have the correct version now and it works very well.
I will close the issue.
Best regards,
Sócrates A Rivera R
